export const CATEGORIES = [
  { value: 'gods', viewValue: 'آلهة' },
  { value: 'numbers', viewValue: 'أرقام' },
  { value: 'family', viewValue: 'عائلة' },
  { value: 'animals', viewValue: 'حيوانات' },
  { value: 'colors', viewValue: 'ألوان' },
  { value: 'food', viewValue: 'طعام' },
  { value: 'body', viewValue: 'جسم' },
  { value: 'symbols', viewValue: 'رموز' },
  { value: 'greetings', viewValue: 'تحيات' },
  { value: 'time', viewValue: 'وقت' },
  { value: 'nature', viewValue: 'طبيعة' },
  { value: 'emotions', viewValue: 'مشاعر' },
  { value: 'clothes', viewValue: 'ملابس' },
  { value: 'music', viewValue: 'موسيقى' },
  { value: 'home', viewValue: 'منزل' },
  { value: 'stones', viewValue: 'أحجار' },
  { value: 'temples', viewValue: 'معابد' },
  { value: 'jobs', viewValue: 'وظائف' },
  { value: 'adjective', viewValue: 'صفات' },
  { value: 'adverb', viewValue: 'ظرف' },
  { value: 'verb', viewValue: 'افعال' },
];
