export const CATEGORIES = [
  { value: 'gods', viewValue: 'آلهة' },
  { value: 'numbers', viewValue: 'أرقام' },
  { value: 'family', viewValue: 'عائلة' },
  { value: 'animals', viewValue: 'حيوانات' },
  { value: 'colors', viewValue: 'ألوان' },
  { value: 'food', viewValue: 'طعام' },
  { value: 'body', viewValue: 'جسم' },
  { value: 'symbols', viewValue: 'رموز' },
  { value: 'greetings', viewValue: 'تحيات' },
  { value: 'time', viewValue: 'وقت' },
  { value: 'nature', viewValue: 'طبيعة' },
  { value: 'emotions', viewValue: 'مشاعر' },
  { value: 'clothes', viewValue: 'ملابس' },
  { value: 'music', viewValue: 'موسيقى' },
  { value: 'home', viewValue: 'منزل' },
  { value: 'stones', viewValue: 'أحجار' },
  { value: 'temples', viewValue: 'معابد' },
  { value: 'jobs', viewValue: 'وظائف' },
  { value: 'adjective', viewValue: 'صفات' },
  { value: 'verb', viewValue: 'افعال' },
  { value: 'words_in_egyptian_dialect', viewValue: 'كلمات في العامية المصرية' },
  { value: 'prepositions', viewValue: 'حروف الجر' },
  { value: 'insects', viewValue: 'حشرات' },
  { value: 'measurements', viewValue: 'قياسات' },
  { value: 'countries', viewValue: 'دول' },
  { value: 'egyptian_cities_provinces', viewValue: 'مدن و محافظات مصرية' },
  { value: 'fruits_vegetables', viewValue: 'فواكه و خضراوات' },
  { value: 'plants', viewValue: 'نباتات' },
  { value: 'cosmos', viewValue: 'الكون' },
];
