export enum CategoryEnum {
  gods = 'gods',
  numbers = 'numbers',
  family = 'family',
  animals = 'animals',
  colors = 'colors',
  food = 'food',
  body = 'body',
  symbols = 'symbols',
  greetings = 'greetings',
  time = 'time',
  nature = 'nature',
  emotions = 'emotions',
  clothes = 'clothes',
  music = 'music',
  home = 'home',
  stones = 'stones',
  temples = 'temples',
  jobs = 'jobs',
  adjective = 'adjective',
  verb = 'verb',
  words_in_egyptian_dialect = 'words_in_egyptian_dialect',
  prepositions = 'prepositions',
  insects = 'insects',
  measurements = 'measurements',
  countries = 'countries',
  egyptian_cities_provinces = 'egyptian_cities_provinces',
  fruits_vegetables = 'fruits_vegetables',
  plants = 'plants',
  cosmos = 'cosmos',
  female_names = 'female_names',
  male_names = 'male_names',
  kings_queens = 'kings_queens',
}

export const CATEGORIES = [
  { value: CategoryEnum.gods, viewValue: 'آلهة' },
  { value: CategoryEnum.numbers, viewValue: 'أرقام' },
  { value: CategoryEnum.family, viewValue: 'عائلة' },
  { value: CategoryEnum.animals, viewValue: 'حيوانات' },
  { value: CategoryEnum.colors, viewValue: 'ألوان' },
  { value: CategoryEnum.food, viewValue: 'طعام' },
  { value: CategoryEnum.body, viewValue: 'جسم' },
  { value: CategoryEnum.symbols, viewValue: 'رموز' },
  { value: CategoryEnum.greetings, viewValue: 'تحيات' },
  { value: CategoryEnum.time, viewValue: 'وقت' },
  { value: CategoryEnum.nature, viewValue: 'طبيعة' },
  { value: CategoryEnum.emotions, viewValue: 'مشاعر' },
  { value: CategoryEnum.clothes, viewValue: 'ملابس' },
  { value: CategoryEnum.music, viewValue: 'موسيقى' },
  { value: CategoryEnum.home, viewValue: 'منزل' },
  { value: CategoryEnum.stones, viewValue: 'أحجار' },
  { value: CategoryEnum.temples, viewValue: 'معابد' },
  { value: CategoryEnum.jobs, viewValue: 'وظائف' },
  { value: CategoryEnum.adjective, viewValue: 'صفات' },
  { value: CategoryEnum.verb, viewValue: 'افعال' },
  {
    value: CategoryEnum.words_in_egyptian_dialect,
    viewValue: 'كلمات في العامية',
  },
  { value: CategoryEnum.prepositions, viewValue: 'حروف الجر' },
  { value: CategoryEnum.insects, viewValue: 'حشرات' },
  { value: CategoryEnum.measurements, viewValue: 'قياسات' },
  { value: CategoryEnum.countries, viewValue: 'دول' },
  {
    value: CategoryEnum.egyptian_cities_provinces,
    viewValue: 'مدن و محافظات',
  },
  {
    value: CategoryEnum.fruits_vegetables,
    viewValue: 'فواكه و خضراوات',
  },
  { value: CategoryEnum.plants, viewValue: 'نباتات' },
  { value: CategoryEnum.cosmos, viewValue: 'الكون' },
  { value: CategoryEnum.female_names, viewValue: 'أسماء أناث' },
  { value: CategoryEnum.male_names, viewValue: 'أسماء ذكور' },
  { value: CategoryEnum.kings_queens, viewValue: 'ملوك وملكات' },
];
